fix(deps): Update dependency exceptiongroup to v1.3.1 (#349)
This PR contains the following updates:

| Package | Update | Change |
|---|---|---|
| [exceptiongroup](https://redirect.github.com/agronholm/exceptiongroup) ([changelog](https://redirect.github.com/agronholm/exceptiongroup/blob/main/CHANGES.rst)) | patch | `==1.3.0` -> `==1.3.1` |

---

### Release Notes

<details>
<summary>agronholm/exceptiongroup (exceptiongroup)</summary>

### [`v1.3.1`](https://redirect.github.com/agronholm/exceptiongroup/releases/tag/1.3.1)

[Compare Source](https://redirect.github.com/agronholm/exceptiongroup/compare/1.3.0...1.3.1)

-   Fixed `AttributeError: 'TracebackException' object has no attribute 'exceptions'` when formatting unpickled TBEs from another Python process which did not apply the `exceptiongroup` patches ([#&#8203;144](https://redirect.github.com/agronholm/exceptiongroup/issues/144))

</details>

---

### Configuration

📅 **Schedule**: Branch creation - Between 12:00 AM and 03:59 AM, on day 1 of the month ( * 0-3 1 * * ) (UTC), Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update again.

---

 - [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check this box

---

This PR has been generated by [Renovate Bot](https://redirect.github.com/renovatebot/renovate).
<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiI0MC4yMi4xIiwidXBkYXRlZEluVmVyIjoiNDAuMjIuMSIsInRhcmdldEJyYW5jaCI6Im1haW4iLCJsYWJlbHMiOlsiYXV0b21lcmdlIl19-->